{{ if .Values.components.rediscli.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rediscli
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      service: rediscli
  template:
    metadata:
      labels:
        service: rediscli
    spec:
      containers:
        - image: {{ .Values.images.rediscli | default "goodsmileduck/redis-cli" }}
          name: rediscli
          resources: {}
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "tail -f /dev/null"]
          env: 
          {{ if eq .Values.redis.enabled false }}
          - name: REDIS_HOST
            value: {{ default "" .Values.redis.host | quote }}
          - name: REDIS_PORT
            value: {{ default "" .Values.redis.port | quote }}
          {{ end }}
      restartPolicy: Always
status: {}
{{ end }}
